### ISSUE TITLE
Connection error when using Eclipse Plugin

### ISSUE THREAD

**Issue by Tharun-rgb** [Checkmarx/ast-eclipse-plugin#121]
There's a connectivity issue I am experiencing when attempting to run a scan using the Checkmarx Eclipse plugin.

I have successfully tested the connection to the Checkmarx server URL using the "Test Connection" feature within the Checkmarx Eclipse plugin, and the result was positive – the connection was successful.

However, when I attempt to run a scan using the same configured settings, I encounter a connection error. The specific error message I receive is: "Connection Error: The cx version is either older than 9.0 or the server can't be reached."

I have version 9.5.5 installed.

I have already gone through a series of troubleshooting steps, including verifying URL configuration and reviewing network connectivity. Despite these efforts, I am unable to resolve the connection error.

**Comment by pedrompflopes** [comment]
Hi @Tharun-rgb  

where do you get the error message ? If you could share a screenshot that would help. 

Thanks.
